Improved ROS setup scripts to better deal with machines where Hydro is not present or even any ROS distro.

diff --git a/conf/ros-select b/conf/ros-select
--- a/conf/ros-select
+++ b/conf/ros-select
@@ -4,6 +4,9 @@ if [[ -d $1 && -f $1/setup.sh ]]; then
 	echo $1 > $HOME/.rosdir
 elif [[ -d /opt/ros/$1 && -f /opt/ros/$1/setup.sh ]]; then
 	echo /opt/ros/$1 > $HOME/.rosdir
+else
+	echo "$1 setup files not found."
+	exit 1
 fi
 
 #ROSDIR=`cat $HOME/.rosdir`
